### ISSUE TITLE
enhancement - combined columns option

### ISSUE THREAD

**Issue by c-nv-s** [gennaro-tedesco/stargazer#9] opened 2021-05-07 01:30 UTC
It would be nice if there was an option to combine all columns so you would have:

NAME | URL | MAIN LANGUAGE | STARS | FORKS

**Comment by gennaro-tedesco** [comment] 2021-05-07 08:37
Good idea, I could probably make this the default command if the program is invoked with username only: something along the lines of 
```
stargazer stats username --> shows stats
stargazer url username --> shows urls

stargazer username --> shows combined information
```
what do you think? I will draft an implementation over the weekend and you may have a look!

**Comment by c-nv-s** [comment] 2021-05-07 10:10
I'm happy to test any updates when i have time.
Thanks for the handy little tool

**Comment by gennaro-tedesco** [comment] 2021-05-07 14:59
I have drafted https://github.com/gennaro-tedesco/stargazer/pull/11 for the change.

Demo: (notice the first call without commands returns a complete dashboard as intended)

![demo](https://user-images.githubusercontent.com/15387611/117468814-5e0e2b80-af55-11eb-9e5c-c121f2ccdcca.gif)

Since the branch isn't released yet if you want to locally test it
```
git clone git@github.com:gennaro-tedesco/stargazer.git && cd stargazer
go install  <-- you must have your Go paths set for this 
stargazer username
```

**Comment by gennaro-tedesco** [comment] 2021-05-08 12:20
I have released a new version containing these changes. Just `go get github.com/gennaro-tedesco/stargazer` to use it. I will close this issue (if you see any newly introduced bugs open a new bug report).

**Closed as completed by gennaro-tedesco** 2021-05-08 12:20 UTC
